apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: championships-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: championships
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
