apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: players-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: players
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
