apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v1
    app: matches
  name: matches
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: matches
  template:
    metadata:
      labels:
        app: matches
        version: v1
        stack: echo
        interface: rest
        language: golang
    spec:
      containers:
        - image: claudioed/matches:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "5Mi"
              cpu: "100m"
            limits:
              memory: "10Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 1
          name: matches
          ports:
            - containerPort: 9999
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 1
