_format_version: "3.0"
_transform: true

services:
  - name: gist-service
    url: https://api.github.com
    routes:
      - name: gists-route
        paths:
          - /gists
  - name: poke-service
    url: https://pokeapi.co/api/v2/pokemon
    routes:
      - name: poke-route
        paths:
          - /poke
    plugins:
      - name: dummy-auth
        config:
          message: "Hello"
